In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm

%matplotlib inline 
%config InlineBackend.figure_format = 'retina' 

sns.set_style(style='white')
sns.set_context(context ='paper')

pd.set_option('max_columns',50)
pd.set_option('max_rows',500)

font_path = 'NanumSquareRoundR.ttf'
fontprop = fm.FontProperties(fname=font_path, size = 15)

In [2]:
indoor = pd.read_csv('indoor_until_day15.csv', encoding = 'euc-kr')

# indoor EDA

In [4]:
indoor.columns = ['SENSOR_ID', 'MEASURE_DTTM',
       'INPUT_TYPE', 'CONNECT_TYPE',
       'LAT', 'LON',
       'TOTAL_ADDR', 'SHOP_NM',
       'PM1_AVG', 'PM1_TOTAL_CNT',
       'PM2_AVG', 'PM2_TOTAL_CNT',
       'PM10_AVG', 'PM10_TOTAL_CNT',
       'TEMPER_AVG', 'TEMPER_TOTAL_CNT',
       'HUMI_AVG', 'HUMI_TOTAL_CNT',
       'TVOC_AVG', 'TVOC_TOTAL_CNT',
       'CO2_AVG', 'CO2_TOTAL_CNT',
       'FORMALDEHYDE_AVG', 'FORMALDEHYDE_TOTAL_CNT',
       'SHARING_YN', 'CAR_YN',
       'BATTERY_INFO', 'SPEED',
       'TOTAL_CNT', 'USE_YN']

In [13]:
indoor.INPUT_TYPE.value_counts()
# 모두 자동

100    477
Name: INPUT_TYPE, dtype: int64

In [18]:
indoor.CONNECT_TYPE.value_counts()
# 100 : 블루투스

200    415
100     62
Name: CONNECT_TYPE, dtype: int64

In [10]:
indoor.CAR_YN.value_counts()

N    443
Y     34
Name: CAR_YN, dtype: int64

In [8]:
indoor.TOTAL_ADDR.value_counts()

서울특별시 구로구 구로동 197-12        310
경기도 수원시 권선구 금곡동 1157          2
서울특별시 강북구 미아동 304-8           1
서울특별시 동작구 신대방동 607-5          1
경기도 안산시 상록구 수암동 41-3          1
경기도 성남시 수정구 신흥동 2460-1        1
경기도 시흥시 조남동 678               1
광주광역시 광산구 신창동 1273-1          1
경기도 성남시 분당구 판교동 494-3         1
경기도 광명시 소하동 1339-1            1
서울특별시 노원구 공릉동 441-26          1
광주광역시 서구 동천동 586              1
서울특별시 강북구 미아동 304-1           1
경기도 수원시 권선구 금곡동 1116-2        1
경기도 안산시 단원구 고잔동 536           1
경기도 시흥시 장곡동 437-5             1
서울특별시 마포구 상암동 487-135         1
경기도 성남시 분당구 백현동 541           1
경기도 성남시 분당구 야탑동 358-3         1
경기도 성남시 분당구 삼평동 681           1
경기도 광명시 광명동 2-21              1
서울특별시 구로구 구로동 811             1
서울특별시 금천구 가산동 60-15           1
경기도 고양시 덕양구 내곡동 189-15        1
서울특별시 종로구 사직동 304-4           1
경기도 고양시 덕양구 원당동 201-77        1
서울특별시 구로구 구로동 212-8           1
전라남도 순천시 서면 압곡리 628-1         1
경기도 수원시 팔달구 인계동 1038-5        1
경기도 시흥시 정왕동 1280-10           1
강원도 춘천시 효자동 627-10            1
경기도 동두천시 지행동 718-3            1
서울특별시 관악구 봉천동 863-3           1
경기도 수원시 장안구 조원동 894           1
서울특별시 마포구 망원동 297-3           1
서울특별시 서대문구 대현동 54-7           1
경기도 의정부시 호원동 426              1
경기도 안양시 동안구 비산동 1112-1        1
경기도 수원시 권선구 세류동 454-15        1
부산광역시 동래구 안락동 1104            1
서울특별시 은평구 불광동 354-10          1
경기도 광명시 하안동 33-3              1
서울특별시 성북구 안암동5가 53            1
서울특별시 성북구 삼선동5가 298-14        1
서울특별시 마포구 도화동 563             1
경기도 성남시 수정구 태평동 7338          1
서울특별시 서대문구 창천동 9-20           1
서울특별시 양천구 신정동 1031-4          1
경기도 성남시 분당구 운중동 35-1          1
경기도 수원시 권선구 권선동 1296-5        1
서울특별시 노원구 중계동 509-1           1
서울특별시 성동구 상왕십리동 750           1
경기도 성남시 중원구 성남동 1758          1
서울특별시 관악구 봉천동 972-28          1
경기도 성남시 분당구 백현동 530           1
경기도 고양시 일산동구 장항동 890-6        1
서울특별시 강동구 길동 184              1
경기도 시흥시 능곡동 761               1
경기도 광명시 광명동 158-515           1
경기도 수원시 영통구 이의동 1381-15       1
서울특별시 서대문구 홍제동 173-4          1
서울특별시 강남구 청담동 343-1           1
서울특별시 용산구 청파동3가 109-20        1
경기도 수원시 영통구 영통동 994-2         1
경기도 성남시 분당구 수내동 15-2          1
서울특별시 성동구 상왕십리동 287           1
서울특별시 송파구 잠실동 29              1
전라남도 광양시 광양읍 죽림리 산87-3        1
강원도 춘천시 조양동 37-20             1
경기도 고양시 덕양구 현천동 666-6         1
경기도 의정부시 의정부동 179-13          1
서울특별시 마포구 서교동 345-1           1
서울특별시 송파구 오금동 51              1
경기도 고양시 일산동구 장항동 769-1        1
경기도 군포시 산본동 1134-2            1
경기도 고양시 덕양구 토당동 809           1
서울특별시 양천구 신정동 900-21          1
서울특별시 동작구 대방동 336-6           1
서울특별시 은평구 불광동 267-1           1
서울특별시 용산구 서빙고동 289            1
경기도 수원시 권선구 권선동 1193-1        1
전라남도 광양시 마동 1051-3            1
경기도 성남시 분당구 수내동 18-3          1
서울특별시 종로구 관철동 12-13           1
서울특별시 금천구 가산동 60-5            1
서울특별시 관악구 신림동 1474-23         1
경기도 고양시 덕양구 내곡동 192-6         1
서울특별시 관악구 신림동 1641-8          1
서울특별시 중구 을지로2가 11             1
서울특별시 광진구 중곡동 230-10          1
경기도 수원시 권선구 구운동 925           1
서울특별시 마포구 도화동 568             1
경기도 안양시 동안구 관양동 1725          1
경기도 수원시 팔달구 인계동 1120          1
서울특별시 금천구 독산동 291-6           1
서울특별시 영등포구 문래동6가 5            1
경기도 안산시 단원구 고잔동 534-1         1
경기도 성남시 수정구 창곡동 산83-1         1
경기도 고양시 일산동구 장항동 784-1        1
경기도 성남시 분당구 금곡동 157           1
경기도 화성시 반송동 42-1              1
경기도 시흥시 광석동 38-1              1
광주광역시 광산구 월곡동 685-1           1
경기도 안양시 동안구 관양동 1746          1
경기도 성남시 수정구 태평동 3677          1
서울특별시 중구 을지로2가 195-8          1
경기도 수원시 영통구 영통동 960-1         1
서울특별시 중구 을지로2가 199-21         1
서울특별시 동작구 상도1동 759            1
서울특별시 금천구 가산동 50-3            1
서울특별시 관악구 봉천동 869-6           1
경기도 양평군 양평읍 공흥리 499-9         1
강원도 춘천시 중앙로2가 32              1
경기도 의정부시 호원동 425              1
서울특별시 강서구 등촌동 657-5           1
경기도 수원시 권선구 서둔동 381           1
서울특별시 은평구 구산동 1-1             1
경기도 의정부시 의정부동 236-1           1
서울특별시 구로구 고척동 253-121         1
경기도 성남시 분당구 서현동 267-3         1
서울특별시 관악구 봉천동 851-19          1
경기도 시흥시 신천동 711               1
경기도 고양시 일산서구 대화동 2222-3       1
서울특별시 동작구 노량진동 54-4           1
인천광역시 남동구 구월동 1271-22         1
서울특별시 마포구 도화동 179-13          1
서울특별시 마포구 노고산동 31-21          1
인천광역시 계양구 작전동 423-3           1
경기도 시흥시 하중동 793-17            1
경기도 안양시 만안구 안양동 674-219       1
서울특별시 강남구 대치동 3-1             1
강원도 춘천시 동내면 거두리 946-1         1
대전광역시 대덕구 대화동 412-1           1
경기도 성남시 분당구 서현동 263           1
경기도 고양시 일산서구 대화동 2602         1
서울특별시 광진구 광장동 218-1           1
경기도 수원시 권선구 금곡동 1118-1        1
경기도 성남시 분당구 서현동 261-6         1
서울특별시 성동구 행당동 286-74          1
서울특별시 구로구 구로동 197-47          1
경기도 부천시 작동 247-2              1
서울특별시 서대문구 연희동 375-12         1
경기도 고양시 일산동구 마두동 764          1
서울특별시 성동구 상왕십리동 811           1
경기도 화성시 병점동 811               1
서울특별시 중구 을지로4가 267-1          1
서울특별시 동작구 사당동 1031-28         1
서울특별시 영등포구 양평동1가 189-2        1
서울특별시 중구 신당동 359-11           1
서울특별시 중랑구 면목동 617-1           1
서울특별시 구로구 개봉동 403-53          1
경기도 시흥시 정왕동 2327-4            1
서울특별시 용산구 이촌동 302-181         1
서울특별시 영등포구 대림동 700-1          1
서울특별시 관악구 신림동 1424-28         1
경기도 고양시 일산동구 장항동 867          1
경기도 안양시 만안구 안양동 674-144       1
서울특별시 중구 을지로2가 6              1
경기도 양주시 옥정동 963-14            1
경기도 성남시 중원구 상대원동 2980-21      1
서울특별시 노원구 공릉동 386-2           1
서울특별시 양천구 목동 602-1            1
경기도 수원시 권선구 금곡동 803-12        1
경기도 성남시 분당구 서현동 275           1
경기도 성남시 분당구 서현동 247-2         1
서울특별시 성북구 길음동 531-22          1
서울특별시 도봉구 창동 13               1
Name: TOTAL_ADDR, dtype: int64